### ISSUE TITLE
Cannot download form Terraform registry

### ISSUE THREAD

**Issue by PeterBurner** [Smartbrood/terraform-aws-ec2-iam-role#2]
When trying to download your module from the Terraform registry I am getting the error  
```
Error: Failed to download module
Could not download module "backend-iam" (main.tf:27) source code from
"https://github.com/Smartbrood/terraform-aws-ec2-iam-role/archive/v0.3.0.tar.gz//*?archive=tar.gz":
bad response code: 404.
```  
  
Looking at your GitHub releases it seems that the download link in the registry is wrong:  
`https://github.com/Smartbrood/terraform-aws-ec2-iam-role/archive/v0.3.0.tar.gz`  
vs  
`https://github.com/Smartbrood/terraform-aws-ec2-iam-role/archive/v0.3.tar.gz`  
  
Could you please fix this?

**Comment by andreynpetrov** [comment]
@PeterBurner Thank you. I added tag v0.3.0 to git repository. It should work now.

**Comment by PeterBurner** [comment]
works now  
thanks
