### ISSUE TITLE
Release 0.5.0 to the registry

### ISSUE THREAD

**Issue by ndench** [Smartbrood/terraform-aws-ec2-iam-role#4]
Version 0.5.0 is not available through the registry as seen here:

![image](https://user-images.githubusercontent.com/2062388/99212059-adc93100-2815-11eb-8b82-219ddf32d13d.png)

Can we release this version to the registry?

**Comment by andreynpetrov** [comment]
Done. https://registry.terraform.io/modules/Smartbrood/ec2-iam-role/aws/latest
